name: mystock_fe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1 
  popup_banner: ^1.0.0
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.6
  string_similarity: ^2.0.0
  flutter_document_picker: ^5.2.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  dio: ^5.4.2+1
  flutter_local_notifications: ^17.0.1
  open_file: ^3.3.2
  file_picker: ^8.0.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
